### ISSUE TITLE
feat: significant figures

### ISSUE THREAD

**Issue by privatenumber** [avoidwork/filesize.js#117]
### Feature description
Would like to set significant figures on the output value.

So, for example, `1 KB` could be outputted as `1.00 KB`.

### Use case
When I have the values in a right-aligned table, the numbers that end with a 0 are truncated and  have different string lengths:
<img width="190" alt="Screen Shot 2020-08-17 at 5 32 23 PM" src="https://user-images.githubusercontent.com/1075694/90446631-b5125e80-e0af-11ea-8c13-828fb58a6c4e.png">

**Comment by ouuan** [comment]
The `pad` option is not significant figures. See https://en.wikipedia.org/wiki/Significant_figures#Rounding_to_significant_figures

**Comment by avoidwork** [comment]
I know; significant figures doesn't matter to me for this lib. PR or it'll never land.

**Comment by ouuan** [comment]
I think significant figures do matter. Let's say you want to see `1.34GB` instead of `1GB` but doesn't want to see `724.16MB` instead of `724MB`. For instance, GitHub Releases is using significant figures:

![screenshot](https://user-images.githubusercontent.com/30581822/122402234-df72c800-cfaf-11eb-8f47-a7ba36f9f66a.png)

If you still think it doesn't matter, I could try drafting a PR.

**Comment by avoidwork** [comment]
Please do, features are driven by other people at this point.
